### ISSUE TITLE
Renaming a database record causes the provider to stop

### ISSUE THREAD

**Issue by heretic098** [Keeper-Security/terraform-provider-secretsmanager#12]
When renaming a "Database" record, e.g. this excerpt from the terraform plan:

    # module.my_module.module.keycloak-db.secretsmanager_database_credentials.vault will be updated in-place
    ~ resource "secretsmanager_database_credentials" "vault" {
            id         = "9nUVfxZDqX2k9z6M8unV2K"
          ~ title      = "module-name-keycloak-postgres" -> "new-module-name-keycloakdb"
            # (4 unchanged attributes hidden)

            # (5 unchanged blocks hidden)
      }

I observe this error:

    │ Error: Plugin did not respond
    │ 
    │   with module.my_module.module.keycloak-db.secretsmanager_database_credentials.vault,
    │   on ../modules/gcp_cloud_sql_db/main.tf line 18, in resource "secretsmanager_database_credentials" "vault":
    │   18: resource "secretsmanager_database_credentials" "vault" {
    │ 
    │ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
    │ more details.
    ╵
    ╷
    │ Error: Plugin did not respond
    │ 
    │   with module.my_module.module.core-db[0].secretsmanager_database_credentials.vault,
    │   on ../modules/gcp_cloud_sql_db/main.tf line 18, in resource "secretsmanager_database_credentials" "vault":
    │   18: resource "secretsmanager_database_credentials" "vault" {
    │ 
    │ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
    │ more details.
    ╵
    
    Stack trace from the terraform-provider-secretsmanager_v1.1.2 plugin:
    
    panic: POST Error: Error: access_denied, message=Record 9nUVfxZDqX2k9z6M8unV2K is not editable
    
    
    goroutine 64 [running]:
    log.(*Logger).Panicln(0xc000354060, {0xc000562e70, 0xc0005a6000, 0xc00033e0f0})
    	log/log.go:238 +0x69
    github.com/keeper-security/secrets-manager-go/core/logger.Panicln(...)
    	github.com/keeper-security/secrets-manager-go/core@v1.3.2/logger/logger.go:165
    github.com/keeper-security/secrets-manager-go/core.(*SecretsManager).PostQuery(0xc000562fa0, {0xc36831, 0xc000562ee0}, {0xb6bb80, 0xc0001367d0})
    	github.com/keeper-security/secrets-manager-go/core@v1.3.2/core.go:601 +0x668
    github.com/keeper-security/secrets-manager-go/core.(*SecretsManager).Save(0xc0007121e0, 0xc0007121e0)
    	github.com/keeper-security/secrets-manager-go/core@v1.3.2/core.go:910 +0xcd
    github.com/keeper-security/terraform-provider-secretsmanager/secretsmanager.resourceDatabaseCredentialsUpdate({0xd41a00, 0xc00083a570}, 0xc000563028, {0xb81f60, 0xc000136c30})
    	github.com/keeper-security/terraform-provider-secretsmanager/secretsmanager/resource_database_credentials.go:304 +0x5c5
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc0003f2e00, {0xd41a00, 0xc00083a570}, 0xd, {0xb81f60, 0xc000136c30})
    	github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/resource.go:741 +0x12e
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003f2e00, {0xd41a00, 0xc00083a570}, 0xc0003400d0, 0xc000826900, {0xb81f60, 0xc000136c30})
    	github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/resource.go:847 +0x9e5
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0003b0348, {0xd41958, 0xc000852200}, 0xc0008440a0)
    	github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/grpc_provider.go:1021 +0xe3c
    github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000236a00, {0xd41a00, 0xc0004acc90}, 0xc000566c40)
    	github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/tf5server/server.go:812 +0x56b
    github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xc06860, 0xc000236a00}, {0xd41a00, 0xc0004acc90}, 0xc00007ec00, 0x0)
    	github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc00029a8c0, {0xd4ef18, 0xc0003144e0}, 0xc00047ab40, 0xc000420660, 0x1235de0, 0x0)
    	google.golang.org/grpc@v1.46.2/server.go:1283 +0xcf2
    google.golang.org/grpc.(*Server).handleStream(0xc00029a8c0, {0xd4ef18, 0xc0003144e0}, 0xc00047ab40, 0x0)
    	google.golang.org/grpc@v1.46.2/server.go:1620 +0xa2a
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
    	google.golang.org/grpc@v1.46.2/server.go:922 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	google.golang.org/grpc@v1.46.2/server.go:920 +0x294
    
    Error: The terraform-provider-secretsmanager_v1.1.2 plugin crashed!
    
    This is always indicative of a bug within the plugin. It would be immensely
    helpful if you could report the crash with the plugin's maintainers so that it
    can be fixed. The output above should help diagnose the issue.
    
The Keeper Secrets Manager app does have edit access to the folder in the Keeper vault. I cannot rename the record myself from the Keeper vault screen which (I assume) is why this error occurs. However given that the contents of the vault are effectively stored in the Terraform state, even if the record were to be deleted and then recreated with the correct information, effectively renaming it, this would be acceptable. I suppose that this would not be something that you would want to do as other things may have been modified by the user in the keeper vault screen, e.g. custom fields and these would be lost on vault recreation. One might argue that modfying by hand things which are being managed under infrastructure as code, like Terraform, means that you're likely to lose the things you've modified.

At the very least this error condition needs to be handled as it prevents other changes that have been made from being completed by Terraform.

I don't have enough knowledge of coding in Go to try this myself. Sorry.

My workaround was to delete the record by hand from the vault and re-run terraform apply. This resulted in a weird state where terraform reported that the vault had been created but it was not visible in the Keeper vault screen. Destroying the vault using terraform destroy -target and then re-running terraform apply again resulted in the record materialising in the Keeper vault correctly.

**Comment by maksimu** [comment]
Hello @heretic098 
We are looking into this issue and have added few additional logs to investigate the cause of this issue. Would it be possible to provide us with the steps on how we can reproduce this issue on our side (along with the steps how you generated configuration file/string)

**Comment by heretic098** [comment]
Hi @maksimu , thanks for looking at this. This terraform file works for me to replicate the problem:

    terraform {
      required_providers {
        secretsmanager = {
          source  = "keeper-security/secretsmanager"
          version = ">= 1.0.0"
        }
      }
    }

    provider "secretsmanager" {
      credential = file("keeper.json")
    }

    variable "ksm_folder_uid" {
      type    = string
      default = "<folder UID>"
    }
    
    variable "ksm_title" {
      type    = string
      default = "test-vault"
    }

    variable "db_host" {
      type    = string
      default = "127.0.0.1"
    }

    variable "user_name" {
      type    = string
      default = "postgres"
    }

    resource "random_password" "password" {
      length  = 128
      special = false # Found an issue in keycloak, special characters result in a database authentication failure
    }

    resource "secretsmanager_database_credentials" "vault" {
      folder_uid = var.ksm_folder_uid
      title      = var.ksm_title

      db_type {
        label    = "type"
        required = false
      }
      host {
        value {
          host_name = "${var.db_host}"
        }
      }
      login {
        value = var.user_name
      }
      password {
        value = random_password.password.result
      }
      file_ref {
        required = false
      }
    }

The steps are:
- Run terraform apply
- Change the value of ksm_title
- Re-run terraform apply

I followed the [KSM docs](https://docs.keeper.io/secrets-manager/secrets-manager/secrets-manager-command-line-interface/init-command) to create keeper.json. `ksm init default <token> --plain`.

Thanks

**Comment by idimov-keeper** [comment]
We just released new version [v1.1.3](https://github.com/Keeper-Security/terraform-provider-secretsmanager/releases/tag/v1.1.3) that addresses the issues with logging and error handling. The error `POST Error: Error: access_denied, message=Record 9nUVfxZDqX2k9z6M8unV2K is not editable` implies that you do not have `Edit` permission in that shared folder. KSM Application permission can be changed after creation (check Application tab in Web Vault for that folder). Also check Settings tab (User and Record permissions). _Newly created records inherit these permissions when adding users or records to this shared folder._

Keeper Vault records use auto-generated identifier UID and when you delete and recreate the record (even if using same title) it will get a new UID.

**Comment by idimov-keeper** [comment]
We also identified and fixed an issue on the back-end allowing clients to create records into a shared folder that is marked read only. The fix will be released soon.

**Comment by craiglurey** [comment]
This issue has been fixed on the backend. The ticket is KA-5187.
