### ISSUE TITLE
Allow to work with subfolders

### ISSUE THREAD

**Issue by pepordev** [Keeper-Security/terraform-provider-secretsmanager#17]
Creating a secret in a subfolder in a shared folder throws an error.

Folder structure:
```
MY SHARED FOLDER
  |
  | my-subfolder-a
    |
    | my-subfolder-b 
```
```
resource "secretsmanager_login" "k8s_oidc" {
  folder_uid = "my-subfolder-b-id"
  title = "token"
  password {
    required = true
    value = "my value"
  }
}
```

If i try to add a secret into `my-subfolder-b` then i got an error
```
│ Error: folder uid='my-subfolder-b' was not retrieved. If you are creating a record in a shared folder that you know exists, make sure that at least one record is present in the folder prior to adding a new record
```

The subfolder does have secrets in it.

**Comment by maksimu** [comment]
Hello @ppodevlab 
Currently our SDKs only support creation of the records in the root of the shared folder. We are working on adding support to regular (non-shared) folders. So, right now `folder_uid` should be a shared folder uid (in your example above it is a UID of "MY SHARED FOLDER" folder)

**Comment by ericrichtert** [comment]
Any update on this?

**Comment by pepordev** [comment]
@maksimu any progress on this one??? this would be really helpful for us.

**Comment by ghost** [comment]
+1, this is a must have

**Comment by maksimu** [comment]
We have added support for the folder management into the SDKs, we will try to work next on the folder management the Terraform provider now.

**Comment by ghost** [comment]
Great news, I look forward to seeing this new feature implemented.
Let me know if you need help testing the TF provider, I am happy to help

**Comment by pepordev** [comment]
> We have added support for the folder management into the SDKs, we will try to work next on the folder management the Terraform provider now.

@maksimu any ETA on this feature? we really would like to have this as it would simplify our workflow quite a bit

**Comment by gotttlieb** [comment]
Any news on the ETA?

**Comment by ghost** [comment]
Hi, any news about this, please?

**Comment by idimov-keeper** [comment]
Release v1.1.4 resolved the issue - allows setting `folder_uid` to any existing sub-folder _(plugin will automatically find its parent shared folder which is also need for create record to succeed)_.
Download it [here](https://github.com/Keeper-Security/terraform-provider-secretsmanager/releases/tag/v1.1.4) or use it directly from Terraform [registry](https://registry.terraform.io/providers/Keeper-Security/secretsmanager/1.1.4)
