### ISSUE TITLE
Write Secrets to Keeper from Module

### ISSUE THREAD

**Issue by PDQDakota** [Keeper-Security/terraform-provider-secretsmanager#2]
Hello!

Would it be possible in any way to write secrets to a vault from Terraform? Or is that something outside the scope of this module?

**Comment by maksimu** [comment]
Very great question! We are currently adding this feature to this provider. Should take a week or so to complete it. Will close this issue once we release this feature

**Comment by maksimu** [comment]
Closing this issue as this feature has been released already. [HERE](https://docs.keeper.io/secrets-manager/secrets-manager/integrations/terraform#create-a-keeper-record) is an example of how to create a record

Also we have published a short [blog post](https://www.keepersecurity.com/blog/2022/05/12/terraform-keeper-secrets-manager/) about record creation

**Comment by tomaaron** [comment]
> Closing this issue as this feature has been released already. [HERE](https://docs.keeper.io/secrets-manager/secrets-manager/integrations/terraform#create-a-keeper-record) is an example of how to create a record
> 
> Also we have published a short [blog post](https://www.keepersecurity.com/blog/2022/05/12/terraform-keeper-secrets-manager/) about record creation

The link leads to a 404. Can you provide the correct link?

**Comment by idimov-keeper** [comment]
The first link provides better examples (also included in the plugin [docs](https://github.com/Keeper-Security/terraform-provider-secretsmanager/tree/master/docs/resources) and [examples](https://github.com/Keeper-Security/terraform-provider-secretsmanager/tree/master/examples/resources) folders)
and [HERE](https://web.archive.org/web/20220720175147/https://www.keepersecurity.com/blog/2022/05/12/terraform-keeper-secrets-manager/) is an alternative to the second link (until the blog  links are fixed)
